INSERT INTO public.axes
(nom, est_actif)
VALUES
('Expérience utilisateur', true),
('Qualités des services numériques', true),
('Intégration du numérique', true),
('Responsabilité sociale', true),
('Conception de services numériques', true),
('Évaluation de la performance', true),
('Expérience employé', true),
('Gouvernance numérique', true);

INSERT INTO public.pratiques
(id_axe, nom, est_actif)
VALUES
((select id from axes where nom='Expérience utilisateur'), 'Comprendre l''utilisateur', true),
((select id from axes where nom='Expérience utilisateur'), 'Tenir compte de l''expérience de l''utilisateur du début à la fin', true),
((select id from axes where nom='Qualités des services numériques'), 'Viser la cohérence et la constance', true),
((select id from axes where nom='Qualités des services numériques'), 'Offrir un service simple et accessible', true),
((select id from axes where nom='Intégration du numérique'), 'Privilégier une interaction en ligne', true),
((select id from axes where nom='Intégration du numérique'), 'Déployer le numérique de bout en bout', true),
((select id from axes where nom='Responsabilité sociale'), 'Déployer des services pour toutes et tous', true),
((select id from axes where nom='Responsabilité sociale'), 'Assurer la sécurité de l''information et la protection des renseignements personnels et confidentiels', true),
((select id from axes where nom='Responsabilité sociale'), 'Concevoir de façon éthique et durable', true),
((select id from axes where nom='Conception de services numériques'), 'Livrer de la valeur rapidement et améliorer en continu', true),
((select id from axes where nom='Conception de services numériques'), 'Choisir des méthodologies et des technologies modernes', true),
((select id from axes where nom='Conception de services numériques'), 'Privilégier la réutilisation et l''interopérabilité', true),
((select id from axes where nom='Évaluation de la performance'), 'Valoriser l''utilisation des données', true),
((select id from axes where nom='Évaluation de la performance'), 'Mesurer la performance pour appuyer les décisions', true),
((select id from axes where nom='Expérience employé'), 'Bâtir une équipe multidisciplinaire et un environnement adapté', true),
((select id from axes where nom='Expérience employé'), 'Former en continu et au bon moment', true),
((select id from axes where nom='Gouvernance numérique'), 'Confirmer et respecter la portée', true),
((select id from axes where nom='Gouvernance numérique'), 'Démontrer une gouvernance transparente', true);

INSERT INTO public.enonces
(id_pratique, texte, reponse_0, reponse_1, reponse_2, reponse_3, reponse_4, est_actif, numero)
VALUES
((select id from pratiques where nom='Comprendre l''utilisateur'),'Notre organisation implique les utilisateurs finaux dans les différentes phases de la conception d’un service numérique.', 'Notre organisation n''implique jamais les utilisateurs finaux.', 'Notre organisation implique les utilisateurs finaux dans 1 phase.', 'Notre organisation implique les utilisateurs finaux dans 2 phases.', 'Notre organisation implique les utilisateurs finaux dans 3 phases.', 'Notre organisation implique les utilisateurs finaux dans 4 phases.', true, 1),
((select id from pratiques where nom='Comprendre l''utilisateur'),'Notre organisation collecte et analyse des données de rétroaction des utilisateurs finaux afin d’améliorer ses services numériques.', 'Notre organisation ne collecte pas de données de rétroaction des utilisateurs finaux.', 'Notre organisation collecte des données de rétroaction de manière informelle (centre de services, courriel, etc.).', 'Notre organisation utilise un outil de collecte de données de rétroaction, mais n''a pas de processus clair pour les analyser.', 'Notre organisation utilise un outil de collecte et analyse des données de rétroaction pour quelques services.', 'Notre organisation utilise un outil de collecte et analyse des données de rétroaction pour la majorité de ses services.', true, 2),
((select id from pratiques where nom='Comprendre l''utilisateur'),'Dans le but de faire évoluer ses services numériques, notre organisation collecte et analyse des données issues de l’historique de navigation des utilisateurs finaux.', 'Notre organisation ne collecte pas de données issues de l''historique de navigation des utilisateurs finaux.', 'Notre organisation collecte des données de manière informelle (centre de services, courriel, etc.).', 'Notre organisation automatise la collecte des données, mais n''a pas de processus pour les analyser.', 'Notre organisation automatise la collecte des données et les analyse pour quelques services.', 'Notre organisation automatise la collecte et les analyse pour la majorité de ses services.', true, 3),
((select id from pratiques where nom='Tenir compte de l''expérience de l''utilisateur du début à la fin'),'Notre organisation possède une stratégie globale d''implication des utilisateurs finaux.', 'Notre organisation ne possède pas de stratégie globale d''implication des utilisateurs finaux.', 'Notre organisation se prépare à l''élaboration d''une stratégie.', 'Notre organisation élabore une stratégie.', 'Notre stratégie possède une stratégie qui n''évolue pas.', 'Notre organisation s''assure que sa stratégie évolue selon les tendances.', true, 4),
((select id from pratiques where nom='Tenir compte de l''expérience de l''utilisateur du début à la fin'),'Notre organisation documente ses parcours utilisateurs.', 'Notre organisation ne documente pas ses parcours utilisateurs.', 'Notre organisation possède un portrait général de ses parcours.', 'Notre organisation documente ses parcours.', 'Notre organisation documente ses parcours et détermine les liens entre eux.', 'Notre organisation positionne ses parcours à l''échelle gouvernementale.', true, 5),
((select id from pratiques where nom='Tenir compte de l''expérience de l''utilisateur du début à la fin'),'Lors de la conception ou de l’évolution d’un service numérique, notre organisation élabore un plan pour la recherche et les essais utilisateurs.', 'Notre organisation n''élabore pas de plans pour la recherche et les essais utilisateurs.', 'Notre organisation prévoit d''élaborer des directives précises concernant l''élaboration de plans pour la recherche et les essais utilisateurs.', 'Notre stratégie globale pour la recherche et les essais utilisateurs suggère un plan pour chaque nouveau service.', 'Notre organisation élabore un plan pour la recherche et les essais utilisateurs pour ses services en conception seulement.', 'Notre organisation élabore un plan pour la recherche et les essais utilisateurs pour ses services en conception et en évolution.', true, 6),
((select id from pratiques where nom='Viser la cohérence et la constance'),'Notre organisation respecte le Programme d’identification visuelle (PIV) gouvernemental (p. ex. normes graphiques, signature) pour ses services numériques.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 7),
((select id from pratiques where nom='Viser la cohérence et la constance'),'Notre organisation uniformise ses modes de prestation de services (p. ex., téléphone, en personne, numérique, etc.) pour assurer une expérience cohérente à l''utilisateur. ', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 8),
((select id from pratiques where nom='Offrir un service simple et accessible'),'Notre organisation optimise ses processus d''affaires.', 'Notre organisation n''optimise jamais ses processus d''affaires.', 'Notre organisation optimise au besoin ses processus d''affaires.', 'Notre organisation profite de la conception et de l''amélioration de certains de ses services pour optimiser ses processus d''affaires.', 'Notre organisation possède un plan d''optimisation pour certains processus d''affaires.', 'Notre organisation possède un plan d''optimisation pour tous ses processus d''affaires.', true, 9),
((select id from pratiques where nom='Offrir un service simple et accessible'),'Notre organisation réutilise l''information déjà connue concernant un utilisateur afin d''éviter à ce dernier de la fournir à nouveau.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 10),
((select id from pratiques where nom='Offrir un service simple et accessible'),'Notre organisation valide l''efficacité des instructions de navigation de ses services numériques.', 'Notre organisation ne valide jamais l''efficacité des instructions de navigation.', 'Notre organisation valide au besoin l''efficacité des instructions de navigation.', 'Notre organisation profite de la conception et de l''amélioration de ses services pour valider l''efficacité des instructions de navigation.', 'Notre organisation valide régulièrement l''efficacité des instructions de navigation pour certains services.', 'Notre organisation valide régulièrement l''efficacité des instructions de navigation pour tous ses services.', true, 11),
((select id from pratiques where nom='Privilégier une interaction en ligne'),'Notre organisation offre ses services en ligne (services numériques).', 'Notre organisation n''offre aucun service en ligne.', 'Notre organisation envisage d''offrir certains de ses services en ligne. ', 'Notre organisation offre 1 service en ligne.', 'Notre organisation offre quelques services en ligne.', 'Notre organisation offre tous ses services en ligne. ', true, 12),
((select id from pratiques where nom='Privilégier une interaction en ligne'),'Notre organisation rend ses services numériques utilisables sur appareils mobiles (p. ex., téléphones intelligents, tablettes).', 'Aucun des services de notre organisation n''est utilisable sur appareils mobiles.', 'Notre organisation envisage de rendre certains de ses services utilisables sur appareils mobiles.', '1 service de notre organisation est utilisable sur appareils mobiles.', 'Quelques services de notre organisation sont utilisables sur appareils mobiles.', 'Tous les services de notre organisation sont utilisables sur appareils mobiles. ', true, 13),
((select id from pratiques where nom='Privilégier une interaction en ligne'),'Notre organisation offre des applications sur appareils mobiles pour ses services numériques.', 'Notre organisation n''offre aucune application sur appareils mobiles.', 'Notre organisation envisage d''offrir une application sur appareils mobiles pour l''un de ses services.', '1 service de notre organisation est utilisable par une application sur appareils mobiles.', 'Quelques services de notre organisation sont utilisables par des applications sur appareils mobiles.', 'Tous les services de notre organisation sont utilisables par des applications sur appareils mobiles.', true, 14),
((select id from pratiques where nom='Déployer le numérique de bout en bout'),'Notre organisation effectue des activités de promotion pour encourager les utilisateurs à se prévaloir de ses services numériques.', 'Notre organisation ne fait aucune promotion de services numériques.', 'Notre organisation envisage de promouvoir ses services numériques.', 'Notre organisation fait occasionnellement la promotion de certains de ses services numériques. ', 'Notre organisation fait régulièrement la promotion de certains de ses services numériques. ', 'Notre organisation fait régulièrement la promotion de tous ses services numériques.', true, 15),
((select id from pratiques where nom='Déployer le numérique de bout en bout'),'Nos services sont numériques de bout en bout (c.-à-d. demande initiale, traitement et retour à l''utilisateur).', 'Aucun service de notre organisation n''est numérique de bout en bout.', 'Notre organisation détermine actuellement des services à rendre numériques de bout en bout.', 'Quelques-uns de nos services sont numériques de bout en bout.', 'Plusieurs de nos services sont numériques de bout en bout.', 'Tous nos services sont numériques de bout en bout.', true, 16),
((select id from pratiques where nom='Déployer le numérique de bout en bout'),'Notre organisation implique l''utilisateur interne dans les différentes phases de la conception d''un service numérique.', 'Notre organisation n''implique jamais l''utilisateur interne.', 'Notre organisation implique l''utilisateur interne dans 1 phase.', 'Notre organisation implique l''utilisateur interne dans 2 phases.', 'Notre organisation implique l''utilisateur interne dans 3 phases.', 'Notre organisation implique l''utilisateur interne dans 4 phases. ', true, 17),
((select id from pratiques where nom='Déployer des services pour toutes et tous'),'Lors des recherches et essais en expérience utilisateur (UX), notre organisation fait participer une diversité d’utilisateurs de ses services numériques.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 18),
((select id from pratiques where nom='Déployer des services pour toutes et tous'),'Notre organisation conçoit des services en tenant compte des différentes situations des utilisateurs (p. ex. limitations physiques, appartenance à un genre, type d’appareil utilisé).', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 19),
((select id from pratiques where nom='Assurer la sécurité de l''information et la protection des renseignements personnels et confidentiels'),'Notre organisation obtient de l''utilisateur uniquement les données indispensables à la prestation du service utilisé.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 20),
((select id from pratiques where nom='Assurer la sécurité de l''information et la protection des renseignements personnels et confidentiels'),'Notre organisation évalue les risques liés à la cybersécurité de ses services numériques.', 'Notre organisation n''évalue pas les risques liés à la cybersécurité.', 'Notre organisation évalue les risques à la demande ou lors d''incidents de cybersécurité. ', 'Notre organisation évalue les risques de cybersécurité selon un calendrier établi à l''avance. ', 'Notre organisation évalue régulièrement les risques liés à la cybersécurité. ', 'Notre organisation évalue les risques liés à la cybersécurité en continu à l''aide des outils appropriés.', true, 21),
((select id from pratiques where nom='Assurer la sécurité de l''information et la protection des renseignements personnels et confidentiels'),'Notre organisation s''assure de réduire les inconvénients des mesures de sécurité et des normes de protection des renseignements personnels (PRP) sur l''expérience de l’utilisateur.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 22),
((select id from pratiques where nom='Concevoir de façon éthique et durable'),'Les services numériques de notre organisation respectent les principes de développement durable (p. ex. diminution de la consommation de papier, réduction des déplacements, etc.).', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 23),
((select id from pratiques where nom='Livrer de la valeur rapidement et améliorer en continu'),'Notre organisation utilise l''approche Agile pour la conception de ses services numériques.', 'Notre organisation n''utilise pas l''approche Agile.', 'Notre organisation est en processus de mettre en place l''approche Agile.', 'Certaines équipes de travail utilisent l''approche Agile.', 'Toutes les équipes de travail utilisent l''approche Agile.  ', 'Toutes les équipes de travail utilisent l''approche Agile et cadencent leurs activités entre elles.', true, 24),
((select id from pratiques where nom='Livrer de la valeur rapidement et améliorer en continu'),'Notre organisation intègre des activités d''expérimentation lors de la conception de ses services.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 25),
((select id from pratiques where nom='Livrer de la valeur rapidement et améliorer en continu'),'Notre organisation intègre des activités de prototypage lors de la conception de ses services.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 26),
((select id from pratiques where nom='Choisir des méthodologies et des technologies modernes'),'Notre organisation considère l''utilisation de technologies innovantes disponibles sur le marché lors de la conception de ses services numériques.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 27),
((select id from pratiques where nom='Choisir des méthodologies et des technologies modernes'),'Les services numériques de notre organisation sont en infonuagique.', 'Aucun des services de notre organisation n’est en infonuagique ', 'Notre organisation envisage le recours à l''infonuagique. ', 'Notre organisation a un projet en cours qui vise le recours à l''infonuagique.', 'Quelques services de notre organisation sont en infonuagique. ', 'La majorité des services numériques de notre organisation sont en infonuagique. ', true, 28),
((select id from pratiques where nom='Privilégier la réutilisation et l''interopérabilité'),'Notre organisation réutilise ou s''inspire des réalisations numériques d''autres organisations.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 29),
((select id from pratiques where nom='Privilégier la réutilisation et l''interopérabilité'),'Les services numériques de notre organisation sont conçus de façon à être interopérables (avoir la capacité de communiquer avec deux ou plusieurs solutions, appareils et éléments informatiques)', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 30),
((select id from pratiques where nom='Privilégier la réutilisation et l''interopérabilité'),'Notre organisation partage avec l''écosystème les retombées de la conception de ses services numériques (p. ex. solutions, code source, résultats d’expérimentation, documentation, bonnes pratiques, etc.).', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 31),
((select id from pratiques where nom='Valoriser l''utilisation des données'),'Notre organisation dispose d''outils pour gérer efficacement les données en lien avec la prestation de ses services. (p. ex. rétroaction des utilisateurs, statistiques d’utilisation, résultat des interactions avec les centres d’appel, gestion des plaintes, etc.).', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 32),
((select id from pratiques where nom='Valoriser l''utilisation des données'),'Pour améliorer la satisfaction des utilisateurs, notre organisation s''appuie sur les données en lien avec la prestation de ses services (p. ex. rétroaction des utilisateurs, statistiques d''utilisation, résultat des interactions avec les centres d’appel).', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 33),
((select id from pratiques where nom='Valoriser l''utilisation des données'),'Notre organisation diffuse dans l''écosystème ses données à haut potentiel de réutilisation.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 34),
((select id from pratiques where nom='Mesurer la performance pour appuyer les décisions'),'Notre organisation dispose d''indicateurs clés de mesure de la performance de ses services numériques.', 'Notre organisation ne dispose pas d''indicateurs clés de mesure de la performance.', 'Notre organisation détermine actuellement ses besoins en matière d''indicateurs clés.', 'Notre organisation dispose d''indicateurs clés pour certains services', 'Notre organisation dispose d''indicateurs clés pour plusieurs services.', 'Notre organisation dispose d''indicateurs clés pour tous ses services.', true, 35),
((select id from pratiques where nom='Mesurer la performance pour appuyer les décisions'),'Notre organisation mesure régulièrement la performance de ses services numériques.', 'Notre organisation n''évalue pas la performance de ses services.', 'Notre organisation évalue, au besoin, la performance de ses services.', 'Notre organisation évalue la performance de ses services selon un calendrier établi à l''avance.', 'Notre organisation évalue régulièrement la performance de ses services.', 'Notre organisation possède les outils afin d''évaluer en continu la performance de ses services.', true, 36),
((select id from pratiques where nom='Mesurer la performance pour appuyer les décisions'),'Pour appuyer sa prise de décision, notre organisation se base sur les résultats de la mesure de la performance de ses services numériques.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 37),
((select id from pratiques where nom='Bâtir une équipe multidisciplinaire et un environnement adapté'),'Notre organisation offre un environnement de travail innovant et propice à la collaboration entre les membres des équipes de travail (p. ex. plateforme de collaboration, espace de partage documentaire, bureaux à aires ouvertes, colocalisation des membres des équipes, etc.).', 'Aucune des équipes ne dispose d''un environnement de travail innovant.', 'Quelques équipes disposent d''un environnement de travail innovant.', 'Plusieurs équipes disposent d''un environnement de travail innovant.', 'Toutes les équipes disposent d''un environnement de travail innovant.', 'Toutes les équipes disposent d''un environnement de travail innovant qui est adapté selon les tendances et les besoins.', true, 38),
((select id from pratiques where nom='Bâtir une équipe multidisciplinaire et un environnement adapté'),'Dans notre organisation, les membres des équipes de travail possèdent des expertises diversifiées et complémentaires.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 39),
((select id from pratiques where nom='Former en continu et au bon moment'),'Notre organisation offre aux équipes de travail la latitude nécessaire pour organiser leurs activités.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 40),
((select id from pratiques where nom='Former en continu et au bon moment'),'Les équipes de travail de notre organisation disposent d''un plan de développement des compétences numériques.', 'Aucune de nos équipes ne dispose d''un plan de développement des compétences numériques.', 'Quelques équipes disposent d''un plan de développement des compétences numériques.', 'Plusieurs équipes disposent d''un plan de développement des compétences numériques.', 'Toutes les équipes disposent d''un plan de développement des compétences numériques.', 'Toutes les équipes disposent d''un plan de développement des compétences numériques qui évolue régulièrement selon les tendances et les nouveaux besoins.', true, 41),
((select id from pratiques where nom='Former en continu et au bon moment'),'Notre organisation encourage les employés à participer à des activités leur permettant de développer les compétences numériques requises dans leur travail.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 42),
((select id from pratiques where nom='Former en continu et au bon moment'),'Les entités de notre organisation ont des processus facilitant le développement des compétences numériques des employés.', 'Aucune des entités ne possède des processus pour le développement des compétences numériques.', 'Notre organisation encourage ses entités à élaborer des processus pour le développement des compétences numériques.', 'Certaines entités possèdent des processus pour le développement des compétences numériques.', 'Plusieurs entités possèdent des processus pour le développement des compétences numériques.', 'Toutes les entités de notre organisation possèdent des processus pour le développement des compétences numériques.', true, 43),
((select id from pratiques where nom='Confirmer et respecter la portée'),'Dans notre organisation, la structure de gouvernance des projets numériques est souple permettant une prise de décision rapide.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 44),
((select id from pratiques where nom='Confirmer et respecter la portée'),'Dans notre organisation, les équipes de travail ont la latitude nécessaire afin d''organiser leur travail.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 45),
((select id from pratiques where nom='Démontrer une gouvernance transparente'),'Notre organisation implique toutes les parties prenantes dans la gouvernance des projets numériques.', 'Notre organisation n''implique pas toutes les parties prenantes. ', 'Notre organisation implique toutes les parties prenantes à la phase de mise en service (déploiement).', 'Notre organisation implique toutes les  parties prenantes aux phases bêta (réalisation) et mise en service (déploiement).', 'Notre organisation implique toutes  les parties prenantes aux phases alpha (DA), bêta (réalisation) et mise en service (déploiement).', 'Notre organisation implique toutes les parties prenantes à toutes les phases. ', true, 46),
((select id from pratiques where nom='Démontrer une gouvernance transparente'),'Dans notre organisation, les équipes de travail communiquent régulièrement l''état d''avancement des initiatives numériques.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 47),
((select id from pratiques where nom='Démontrer une gouvernance transparente'),'Dans notre organisation, les équipes de travail disposent des moyens nécessaires afin de pouvoir escalader les éléments bloquants.', 'Pas du tout d''accord / Jamais le cas', 'Un peu d''accord / Rarement le cas', 'Moyennement d''accord / Parfois le cas', 'Assez d''accord / Souvent le cas', 'Tout à fait d''accord / Toujours le cas', true, 48);

INSERT INTO public.lexique
(mot, definition)
VALUES
('Approche Agile', '1-L''Agilité'),
('Cybersécurité', '1-Capacité, pour un système en réseau, de se protéger et de résister à des événements issus du cyberespace'),
('Service numérique', 'Service offert en ligne et accessible par des moyens numériques'),
('Stratégie globale', 'Stratégie'),
('Technologie innovante (c''est large)', 'https://www.crim.ca/fr/expertises-et-technologies');

INSERT INTO public.organisations
(nom, est_actif)
VALUES
('Organisation 1', true),
('Organisation 2', true),
('Organisation 3', true),
('Organisation 4', true),
('Organisation 5', true);

INSERT INTO public.organisateurs
(id_organisation, nom, prenom, courriel, est_actif)
VALUES
((select id from organisations where nom='Organisation 1'), 'Doe', 'Jane', 'jane.doe@email.com', true),
((select id from organisations where nom='Organisation 5'), 'Doe', 'John', 'john.doe@email.com', true),
((select id from organisations where nom='Organisation 1'), 'Tremblay', 'Jean-Philippe', 'jean-philippe.tremblay@email.com', true);

INSERT INTO public.seances
(id_organisation, participants, est_officiel)
VALUES
((select id from organisations where nom='Organisation 1'), ARRAY ['Francis', 'Pierre', 'Marc-André'], true),
((select id from organisations where nom='Organisation 1'), ARRAY ['Francis', 'Nathan', 'Marc-André'], true),
((select id from organisations where nom='Organisation 1'), ARRAY ['Viviane', 'Pierre', 'Marc-André'], true);

INSERT INTO public.reponses
(id_seance, id_enonce, type_reponse)
VALUES
((select s.id from seances s, organisations o where s.participants = ARRAY ['Francis', 'Pierre', 'Marc-André']
and s.id_organisation = (select id from organisations where nom = 'Organisation 1') and s.id_organisation = o.id group by s.id), (select id from enonces where numero=1), '4'),
((select s.id from seances s, organisations o where s.participants = ARRAY ['Francis', 'Nathan', 'Marc-André']
and s.id_organisation = (select id from organisations where nom = 'Organisation 1') and s.id_organisation = o.id group by s.id), (select id from enonces where numero=2), '0'),
((select s.id from seances s, organisations o where s.participants = ARRAY ['Viviane', 'Pierre', 'Marc-André']
and s.id_organisation = (select id from organisations where nom = 'Organisation 1') and s.id_organisation = o.id group by s.id), (select id from enonces where numero=2), '2');